repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/MarketSquare/robotframework-tidy
    rev: 4.15.0
    hooks:
      - id: robotidy

  - repo: https://github.com/MarketSquare/robotframework-robocop
    rev: 5.6.0
    hooks:
      - id: robocop
        args: ["--threshold", "W"]
